#!/bin/bash         
cd "$(dirname "$0")"

pushd output/fingerprint-client
mvn package
popd

pushd output/fingerprint-server
mvn package
popd

cp output/fingerprint-client/target/fpclient-swagger-codegen-1.0.0.jar ../webapi/codegen
cp output/fingerprint-server/target/fpserver-swagger-codegen-1.0.0.jar ../webapi/codegen
cp modules/swagger-codegen-cli/target/swagger-codegen-cli.jar ../webapi/codegen

